FROM ubuntu
LABEL author="Rune Skovrup Hansen"
LABEL version="1.0"
LABEL description="Ubuntu container to show how metadata can be added to a container \
while bulding using the LABEL instruction"

# Output of inspecting the image after building:

# ...
# "Labels": {
#                "author": "Rune Skovrup Hansen",
#                "description": "Ubuntu container to show how metadata can be added to a container while bulding using the LABEL instruction",
#                "version": "1.0"
#            }
# ...
